### ISSUE TITLE
Calculate Stats - Change Required

### ISSUE THREAD

**Issue by rootanand** [rex-alan/Billing_Application_c-#1]
- [x] There is no calculation involved in this class.
- [x] Then why name it as such?
- [x] Where will you calculate the discount and gst, then?

**Comment by rex-alan** [comment]
1) Now, I have done calculations in Calculate_Stats
2) It is renamed to Bill_Stats
3) Discount and Gst are calculated in Calculate_Stats and the values are not shown only the final amount of the product is shown in the bill
